server:
  port: 80
  servlet:
    path: /es-management

elasticsearch:
  host: http://49.4.9.225:9200
  username:
  password:
  index:
    user: user-filebeat
    resources: res-filebeat
    admin: admin-filebeat
    system: system-filebeat
    userAccess: user-access-count
    userLogin: user-login-count
    resourceAccess: res-access-count
    logSetting: .log-setting
    appLibrary: .app-library

