server:
  port: 80
  servlet:
    path: /es-management

elasticsearch:
  hosts: 49.4.9.225:9200
  username:
  password:
  index:
    user: user-filebeat
    resources: res-filebeat
    admin: admin-filebeat
    system: system-filebeat
    logSetting: .log-setting
    logDownload: .log-download
    appLibrary: .app-library
    topRanking: top-ranking
    filebeat: filebeat
  # 查询相关设置
  query:
    maxTotal: 10000
  # 统计周期
  count:
    cycles: day,month,year
  # 别名相关设置
  aliases:
    # 别名前缀
    prefixs: user,admin,res,system