server:
  port: 80
  servlet:
    path: /es-management

elasticsearch:
  hosts: 49.4.9.225:9200
  username:
  password:
  index:
    logSetting: .log-setting
    logDownload: .log-download
    appLibrary: .app-library
    topRanking: top-ranking
  # 查询相关设置
  query:
    maxTotal: 10000
  # 统计周期
  count:
    cycles: day,month,year
  # 别名相关设置
  aliases:
    # 别名前缀
    prefixs: user,admin,res,system
  filebeat:
    version: 6.3.1
    index: filebeat
  metribeat:
    version: 6.3.1
    # 临时文件保存路径
  file:
    tmp: /tmp/es/
    download: /tmp/es/download/